[package]
name = "amatl-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
amatl-core = { version = "0.1.0-rc.1", path = "../amatl-core" }
amatl-ui = { version = "0.1.0-rc.1", path = "../amatl-ui" }
axum.workspace = true
axum-server.workspace = true
hyper-util.workspace = true
rmcp.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true

[lints]
workspace = true

[dev-dependencies]
rcgen = "0.14.8"
reqwest.workspace = true
tracing-subscriber.workspace = true
